#!/usr/bin/env bash

source ./project

RED='\033[0;31m'
NOCOLOR='\033[0m'

_script_name="$(basename -- "${BASH_SOURCE[0]}")"

PATH_REPO_ROOT="$(realpath "$(dirname -- "${BASH_SOURCE[0]}")")"
echo "Preparing $PROJECT_NAME located at $PATH_REPO_ROOT"

PATH_VENDORS="$PATH_REPO_ROOT/vendor"

PATH_GODOT="$(realpath "$(which $(cat .godot-path))")"
echo "godot executable located at $PATH_GODOT"

if [[ -L "$PATH_REPO_ROOT"/godot ]]; then
    rm "$PATH_REPO_ROOT"/godot
fi
ln -s $PATH_GODOT godot

# Update submodules

# Update godot-cpp
PATH_GODOT_CPP="$PATH_VENDORS"/godot-cpp
echo "godot-cpp located at $PATH_GODOT_CPP"
cd "$PATH_VENDORS"/godot-cpp
git submodule update --init --recursive

echo "Dumping extension_api.json into repository root..."
cd $PATH_REPO_ROOT
$PATH_GODOT --headless --dump-extension-api

echo "Dumping extension_api.json and gdextension_interface.h into godot-cpp..."
cd $PATH_GODOT_CPP/gdextension
$PATH_GODOT --headless --dump-extension-api --dump-gdextension-interface
